[connections.default]
# Snowflake account configuration for CI/CD
account = "SFSENORTHAMERICA-DODICSE"
user = "github_actions_user"
password = "PLACEHOLDER_PASSWORD"
database = "MAMMOTH"
schema = "PUBLIC"
warehouse = "DEMO_WH"
role = "STREAMLIT_CICD_ROLE"

[streamlit]
# Streamlit app configuration
name = "nga_imagery_intelligence_app"
file = "nga_imagery_intelligence_app.py"
warehouse = "DEMO_WH"
title = "NGA Imagery Intelligence Platform" 